<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="track_radius" value="0.04"/>
    <xacro:property name="track_length" value="0.27"/>
    <xacro:property name="track_width" value="0.04"/>
   

    
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0.075"/>
            <geometry>
                <box size="0.3 0.3 0.15"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.075"/>
            <geometry>
                <box size="0.3 0.3 0.15"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
            <origin xyz="0 0 0.075" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>
    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.2 0" rpy="0 0 0" />

    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <box size="${2*track_radius - track_length} ${track_width} ${track_radius*2} "/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${2*track_radius - track_length} ${track_width} ${track_radius*2} "/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${2*track_radius - track_length}" y="${track_width}" z="${track_radius*2}" >
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>


        <visual> 
            <origin xyz="${track_length/2 + - track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${track_length/2 + - track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.05" length="${track_radius}" radius="${track_width}">
            <origin xyz="${track_length/2 + - track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:inertial_cylinder>

        <visual> 
            <origin xyz="${-track_length/2 + track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${-track_length/2 + track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.05" length="${track_radius}" radius="${track_width}">
            <origin xyz="${-track_length/2 + track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.2 0" rpy="0 0 0" />
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <box size="${2*track_radius - track_length} ${track_width} ${track_radius*2} "/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${2*track_radius - track_length} ${track_width} ${track_radius*2} "/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${2*track_radius - track_length}" y="${track_width}" z="${track_radius*2}" >
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>

        <visual>
            <origin xyz="${track_length/2 + - track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${track_length/2 + - track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.05" length="${track_radius}" radius="${track_width}">
            <origin xyz="${track_length/2 + - track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>

        </xacro:inertial_cylinder>

        <visual>
            <origin xyz="${-track_length/2 + track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${-track_length/2 + track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.05" length="${track_radius}" radius="${track_width}">
            <origin xyz="${-track_length/2 + track_radius} 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo
        reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
</robot>